import Head from 'next/head'
import {
  Heading,
  Avatar,
  Box,
  Center,
  Text,
  Stack,
  Button,
  Link,
  Grid,
  useColorModeValue,
  Flex,
} from '@chakra-ui/react';
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {RxDotFilled} from 'react-icons/rx'
import {FcFile} from 'react-icons/fc'

export default function Home({github}) {
  // const {
  //   html_url,
  // //   name,
  //   description,
  //   stargazers_count,
  //   forks_count,
  //   language,
  // } = github.items
  // console.log(github.items)
  github.items.map((el) => console.log(el))
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex gap='10px' justifyContent={'space-between'}>
          <Box>
             <Box>
              <SocialProfileSimple />
             </Box>
             <Box  maxW={'320px'}
        w={'full'}
        bg={useColorModeValue('white', 'gray.900')}
        boxShadow={'2xl'}
        rounded={'lg'}
        p={6}
        textAlign={'center'}>
                <Text textAlign={'center'}
          color={useColorModeValue('gray.700', 'gray.400')}
          px={3} >
            Full-stack Developer | JavaScript | Typescript | NodeJS | ReactJS | HTML | CSS | Chakra-UI
          </Text>
             </Box>
          </Box>
          <Box w={'100%'}>
       <Grid m={'auto'}>
        <Box margin={'auto'}>
          <a href={`https://github.com/sejal710?tab=repositories`}>
             <Text fontSize={'40px'} fontWeight='10px'>Project</Text>
          </a>
        </Box>
        <Box>
          <Grid gridTemplateColumns={'repeat(3,1fr)'} gap='15px'>
            {github.items.map((item, index) => <Project key={index} {...item} />)}
          </Grid>
        </Box>
      </Grid>
          </Box>
        </Flex>
       

      </main>
    </>
  )
}
export async function getServerSideProps(){
  let res = await fetch(`https://api.github.com/search/repositories?q=user:sejal710+fork:true&sort=updated&per_page=8&type=Repositories`)
  let data = await res.json()
  return {
    props : {
      github :data
    } // will be passed to the page component as props
  }
}
function SocialProfileSimple() {
  return (
    <Center py={6}>
      <Box
        maxW={'320px'}
        w={'full'}
        bg={useColorModeValue('white', 'gray.900')}
        boxShadow={'2xl'}
        rounded={'lg'}
        p={6}
        textAlign={'center'}>
        <Avatar
          size={'xl'}
          src={
            'https://avatars.githubusercontent.com/u/108399174?s=400&u=a94313ba35c589a292cd0f61d8e91fafdb9a485f&v=4'
          }
          alt={'Avatar Alt'}
          mb={4}
          pos={'relative'}
          _after={{
            content: '""',
            w: 4,
            h: 4,
            bg: 'green.300',
            border: '2px solid white',
            rounded: 'full',
            pos: 'absolute',
            bottom: 0,
            right: 3,
          }}
        />
        <Heading fontSize={'2xl'} fontFamily={'body'}>
          Sejal Jaiswal
        </Heading>
        <Text fontWeight={600} color={'gray.500'} mb={4}>
         710sejal@gmail.com
        </Text>
        <Text
          textAlign={'center'}
          color={useColorModeValue('gray.700', 'gray.400')}
          px={3}>
          Full-stack Developer |  JavaScript | Typescript | NodeJS | ReactJS | HTML | CSS | Chakra-UI 
        </Text>


        <Stack mt={8} direction={'row'} spacing={4}>
          <Button
            flex={1}
            fontSize={'sm'}
            rounded={'full'}
            _focus={{
              bg: 'gray.200',
            }}>
              <a href='https://drive.google.com/file/d/1cGcCIxgaPzXIjRjcu09ZErU98GUzQK7f/view?usp=share_link'>
                Resume
              </a>
            
          </Button>
          <Button
            flex={1}
            fontSize={'sm'}
            rounded={'full'}
            bg={'blue.400'}
            color={'white'}
            boxShadow={
              '0px 1px 25px -5px rgb(66 153 225 / 48%), 0 10px 10px -5px rgb(66 153 225 / 43%)'
            }
            _hover={{
              bg: 'blue.500',
            }}
            _focus={{
              bg: 'blue.500',
            }}>
              <a href='https://github.com/sejal710'>Follow</a>
            
          </Button>
        </Stack>
      </Box>
    </Center>
  );
}

function Project ({
  html_url,
  name,
  description,
  stargazers_count,
  forks_count,
  language,
}){
  return (
    <a href={html_url}>
       <Box  maxW={'320px'}
        w={'full'}
        bg={useColorModeValue('white', 'gray.900')}
        boxShadow={'2xl'}
        rounded={'lg'}
        p={6}>
          <Grid gap='9px'>
            <Box>
              <Flex>
                <Text fontSize={'20px'} fontWeight='15px' display={'flex'} gap='10px' justifyContent={'center'}
                alignItems='center'>
                  <span><FcFile /></span> {name}</Text></Flex>
            </Box>
            <Box>
              <Text>{description}</Text>
            </Box>
            <Box>
              <Flex>
              <Text fontSize={'20px'} fontWeight='15px' display={'flex'} gap='10px' justifyContent={'center'}
                alignItems='center'><span><RxDotFilled /></span>{language}</Text></Flex>
            </Box>
          </Grid>
       </Box>
    </a>
  );
     
}
